version: '3'
services:
  db:
    image: mysql:8.0
    container_name: review-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: inno
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
#    volumes:
#      - ./db/mysql/data:/var/lib/mysql
#      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64